# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SHAD Student Blog
#email: your-email@domain.com
description: >
  This is the test area for a SHAD Student Blog, made with Jekyll.
baseurl: "/shadblog" # the subpath of your site, e.g. /blog
url: "http://matthewwang.me/" # the base hostname & protocol for your site
github_username:  malsf21

# Build settings
markdown: kramdown
